### PR TITLE
Fixing client end compilation and dependency issues

### LINKED ISSUE #6: Detected vulnerable npm dependencies
**Describe the bug**
Current tensormap client project is not having the latest npm modules. This enforces a threat on security side as there are vulnerable npm packages as dependencies.

**To Reproduce**

Navigate to client project and run 'npm audit'

**Expected behavior**
Should list number of vulnerabilities along with the vulnerable packages.

**Screenshots**
image

Following are the identified vulnerable packages.
@adobe/css-tools  <=4.3.1
Severity: moderate

@babel/traverse  <7.23.2
Severity: critical

axios  0.8.1 - 0.27.2
Severity: moderate

follow-redirects  <1.15.4
Severity: moderate

nth-check  <2.0.1
Severity: high

postcss  <8.4.31
Severity: moderate

semver  6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
Severity: moderate

tough-cookie  <4.1.3
Severity: moderate

word-wrap  <1.2.4
Severity: moderate

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome

### LINKED ISSUE #18: Upgrading React-Router-Dom
Make routing on the client side a lot smmother and cleaner

**Describe the solution you'd like**
Upgrade from the current v5 of react-router-dom to v6 will give us the following benefits:
- Hooks-Based API: Version 6 introduces a hooks-based API, aligning closely with React's functional programming paradigm. It provides a consistent and predictable way to manage state and side effects within your components.
- Improved Nesting: Nesting routes in v6 is more straightforward and flexible. The new `Routes` component replaces the old `Switch` component, allowing for better nesting and composition of route components.
- Automatic Route Matching: V6 simplifies the process of route matching, making it more intuitive. Routes are matched based on their order of definition, eliminating the need for exact and strict prop usage.
- Simpler Redirects: Redirects are simplified in v6, making it more convenient to handle redirections within your application.
- Dynamic Imports: V6 encourages the use of dynamic imports for code splitting, allowing you to load route components asynchronously and improving performance.

### PR DESCRIPTION
**Pull request by Teak-Rosewood**
# Description

The current situation as it stands is that all the react components compile, there are a few linting errors but it has greatly reduced from the 300s to the 100s and the website on the front end compiles all the wbpages with routing.

react-router-dom has been updated to the latest version with the specified code changes in app.jsx, and a lot of js files have been changed to jsx to allow it to return html components.

Fixes #6 
Fixes #18 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Currently, the codebase doesnt have a navbar so the tests for those are failing, furthermore the app.js test is a test for the basic react app icon which it is also failing, proper tests have to be published to account for the same, i am working on that as well

Screenshot from 2024-02-27 11-12-03
Screenshot from 2024-02-27 11-11-53
Screenshot from 2024-02-27 11-11-45
Screenshot from 2024-02-27 11-16-33

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

Website Screenshots of compiling:
Screenshot from 2024-02-27 11-18-12
Screenshot from 2024-02-27 12-38-42
Screenshot from 2024-02-27 11-17-34
Screenshot from 2024-02-27 11-17-23

The error network issue is due to its lack of connection to the backend, which i am actively working on solving.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Teak-Rosewood** [comment]
I have also moved from react-scripts to vite as it removes 15 high severity vulnerability to 1 moderate severity

**Review by ivantha — CHANGES_REQUESTED** [review]
@Teak-Rosewood It would be nice If you could only submit the fixes and not "moving to Vite".

**Comment by Teak-Rosewood** [comment]
integrated the navbar and sidebar into the website components after changing it to functional code
Screenshot from 2024-02-29 17-51-51
Screenshot from 2024-02-29 17-51-43
Screenshot from 2024-02-29 17-51-35
Screenshot from 2024-02-29 17-51-27

**Comment by Teak-Rosewood** [comment]
all tests are now passing
Screenshot from 2024-02-29 21-49-07

**Comment by ivantha** [comment]
@Teak-Rosewood Why have we converted js files to jsx?

**Comment by Teak-Rosewood** [comment]
As per my knowledge a pure .js file is used to state that the file doesn't have any reactified components, both can be used interchangeably but it's conventional to use jsx for files that return html components. That's why I have converted the .js files to .jsx to identify javascript that returns html vs js that doesn't return jsx, the linter also gave me errors for the same. I can change it back if needed

**Pull request closed without merging**
